import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1765110810291 implements MigrationInterface {
    name = 'InitialSchema1765110810291'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`companies\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`slug\` varchar(100) NOT NULL, \`email\` varchar(255) NULL, \`phone\` varchar(50) NULL, \`currency\` enum ('USD', 'EUR', 'GBP', 'JPY', 'CNY', 'CHF', 'CAD', 'AUD', 'NZD', 'SGD', 'HKD', 'KES', 'TZS', 'UGX', 'ZAR', 'NGN', 'EGP', 'GHS', 'RWF', 'ETB', 'AED', 'SAR', 'INR', 'PKR', 'BRL', 'MXN') NOT NULL DEFAULT 'USD', \`timezone\` varchar(50) NOT NULL DEFAULT 'UTC', \`email_settings\` json NULL, \`reminder_preferences\` json NULL, \`branding\` json NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_b28b07d25e4324eee577de5496\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`first_name\` varchar(100) NOT NULL, \`last_name\` varchar(100) NOT NULL, \`email\` varchar(255) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`role\` enum ('SUPER_ADMIN', 'OWNER', 'ADMIN', 'STAFF', 'AUDITOR', 'TENANT_PORTAL') NOT NULL DEFAULT 'STAFF', \`is_super_admin\` tinyint NOT NULL DEFAULT 0, \`status\` enum ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING') NOT NULL DEFAULT 'ACTIVE', \`profile\` json NULL, \`last_login_at\` timestamp NULL, \`last_login_ip\` varchar(45) NULL, \`email_verified_at\` timestamp NULL, \`verification_token\` varchar(255) NULL, \`reset_token\` varchar(255) NULL, \`reset_token_expires_at\` timestamp NULL, INDEX \`IDX_7ae6334059289559722437bcc1\` (\`company_id\`), INDEX \`IDX_ace513fa30d485cfd25c11a9e4\` (\`role\`), INDEX \`IDX_13af76739939fc5cb3c90ab3e7\` (\`company_id\`, \`status\`), UNIQUE INDEX \`IDX_074675ed1a1d59bfe7bdb9c0a3\` (\`company_id\`, \`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`compounds\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`address_line\` varchar(500) NOT NULL, \`city\` varchar(100) NOT NULL, \`region\` varchar(100) NULL, \`country\` varchar(100) NOT NULL, \`geo_lat\` decimal(10,7) NULL, \`geo_lng\` decimal(10,7) NULL, \`notes\` text NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, INDEX \`IDX_3b301e23108ca93e9722cef76f\` (\`company_id\`), INDEX \`IDX_8209df35c059494e5385f81619\` (\`company_id\`, \`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`apartments\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`compound_id\` varchar(255) NOT NULL, \`unit_number\` varchar(50) NOT NULL, \`floor\` int NULL, \`bedrooms\` int NULL, \`bathrooms\` int NULL, \`area_sqm\` decimal(10,2) NULL, \`monthly_rent\` decimal(15,2) NULL, \`status\` enum ('available', 'occupied', 'maintenance', 'reserved') NOT NULL DEFAULT 'available', \`amenities\` json NULL, \`notes\` text NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, INDEX \`IDX_4c561cc9a0dbc7a155eb67a930\` (\`company_id\`), INDEX \`IDX_55d37c286a265d21050cae70d2\` (\`compound_id\`), INDEX \`IDX_bc79e8864b14bbeec8ea1b3e69\` (\`company_id\`, \`is_active\`), UNIQUE INDEX \`IDX_febf85cc220bd9dd7944ad9f46\` (\`company_id\`, \`compound_id\`, \`unit_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`occupancies\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`tenant_id\` varchar(255) NOT NULL, \`apartment_id\` varchar(255) NOT NULL, \`lease_start_date\` date NOT NULL, \`lease_end_date\` date NOT NULL, \`monthly_rent\` decimal(15,2) NOT NULL, \`security_deposit\` decimal(15,2) NULL, \`deposit_paid\` decimal(15,2) NOT NULL DEFAULT '0.00', \`move_in_date\` date NULL, \`move_out_date\` date NULL, \`status\` enum ('pending', 'active', 'ended', 'cancelled') NOT NULL DEFAULT 'pending', \`notes\` text NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, INDEX \`IDX_ede495d4327cd721ce175a8511\` (\`company_id\`), INDEX \`IDX_cc434c1f52c60c9798f1b78c8a\` (\`company_id\`, \`lease_end_date\`), INDEX \`IDX_4d90e617c11658ff4d517c796c\` (\`company_id\`, \`tenant_id\`, \`status\`), INDEX \`IDX_32c4561f4cc180f79bc0fdb43f\` (\`company_id\`, \`apartment_id\`, \`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tenants\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`first_name\` varchar(100) NOT NULL, \`last_name\` varchar(100) NOT NULL, \`email\` varchar(255) NOT NULL, \`phone\` varchar(50) NULL, \`alternate_phone\` varchar(50) NULL, \`date_of_birth\` date NULL, \`id_type\` varchar(50) NULL, \`id_number\` varchar(100) NULL, \`current_address\` text NULL, \`emergency_contact_name\` varchar(100) NULL, \`emergency_contact_phone\` varchar(50) NULL, \`emergency_contact_relationship\` varchar(100) NULL, \`employer_name\` varchar(255) NULL, \`employer_phone\` varchar(100) NULL, \`monthly_income\` decimal(15,2) NULL, \`references\` json NULL, \`documents\` json NULL, \`notes\` text NULL, \`status\` enum ('active', 'inactive', 'blacklisted') NOT NULL DEFAULT 'active', \`is_active\` tinyint NOT NULL DEFAULT 1, INDEX \`IDX_a12aa6f8ff1f37c2f46d3c8d2d\` (\`company_id\`), INDEX \`IDX_4575399619ef02e945a891594c\` (\`company_id\`, \`is_active\`), INDEX \`IDX_43a378face32c5050980a0f26b\` (\`company_id\`, \`phone\`), UNIQUE INDEX \`IDX_cc30a75ec408eb5b3e40d2ef87\` (\`company_id\`, \`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invoices\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`invoice_number\` varchar(50) NOT NULL, \`occupancy_id\` varchar(255) NOT NULL, \`tenant_id\` varchar(255) NOT NULL, \`invoice_date\` date NOT NULL, \`due_date\` date NOT NULL, \`status\` enum ('draft', 'sent', 'paid', 'overdue', 'cancelled') NOT NULL DEFAULT 'draft', \`lineItems\` json NOT NULL, \`subtotal\` decimal(15,2) NOT NULL, \`tax_amount\` decimal(15,2) NULL DEFAULT '0.00', \`total_amount\` decimal(15,2) NOT NULL, \`amount_paid\` decimal(15,2) NOT NULL DEFAULT '0.00', \`notes\` text NULL, \`paid_date\` date NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, INDEX \`IDX_42385e42f092f26bd38df54971\` (\`company_id\`), UNIQUE INDEX \`IDX_c72926e1735b41a93b9c5f57c0\` (\`company_id\`, \`invoice_number\`), INDEX \`IDX_ea4aed7c8a6b574f4d9b79c3bf\` (\`company_id\`, \`due_date\`), INDEX \`IDX_c1cc6a2e57fddf1d677f88d7b6\` (\`company_id\`, \`tenant_id\`, \`status\`), INDEX \`IDX_668775b9dc46cd6402210bd919\` (\`company_id\`, \`occupancy_id\`, \`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reminders\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`type\` enum ('DUE_SOON', 'OVERDUE', 'RECEIPT', 'WELCOME') NOT NULL, \`tenant_id\` varchar(255) NOT NULL, \`invoice_id\` varchar(255) NULL, \`subject\` varchar(255) NOT NULL, \`message\` text NOT NULL, \`recipient\` varchar(255) NULL, \`status\` enum ('PENDING', 'SENT', 'FAILED') NOT NULL DEFAULT 'PENDING', \`scheduled_for\` timestamp NOT NULL, \`sent_at\` timestamp NULL, \`error_message\` text NULL, \`retry_count\` int NOT NULL DEFAULT '0', \`metadata\` json NULL, INDEX \`IDX_e97a544f921f6767cd9f31e767\` (\`company_id\`), INDEX \`IDX_d61cc4c5af3a45f1b999b5b2c4\` (\`company_id\`, \`tenant_id\`), INDEX \`IDX_1793350b2155aa2ce6317cf4f7\` (\`company_id\`, \`status\`, \`scheduled_for\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payments\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`invoice_id\` varchar(255) NOT NULL, \`amount\` decimal(15,2) NOT NULL, \`paid_at\` timestamp NOT NULL, \`method\` enum ('CASH', 'BANK', 'MOBILE', 'CARD', 'OTHER') NOT NULL, \`reference\` varchar(255) NULL, \`metadata\` json NULL, \`idempotency_key\` varchar(255) NULL, \`notes\` text NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, INDEX \`IDX_4781cf05f36ba314cdd314c0c6\` (\`company_id\`), UNIQUE INDEX \`IDX_66ef2a22355829d25ca16b4d26\` (\`company_id\`, \`idempotency_key\`), INDEX \`IDX_b557b05b082296d4daacaaa5dd\` (\`company_id\`, \`paid_at\`), INDEX \`IDX_96dd5920faa78291a24a5df5c5\` (\`company_id\`, \`invoice_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_7ae6334059289559722437bcc1c\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`apartments\` ADD CONSTRAINT \`FK_55d37c286a265d21050cae70d2a\` FOREIGN KEY (\`compound_id\`) REFERENCES \`compounds\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`occupancies\` ADD CONSTRAINT \`FK_c2efa500cba606fc34d8ddaafbe\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`occupancies\` ADD CONSTRAINT \`FK_e136b5566e6dba72d8f389a68bf\` FOREIGN KEY (\`apartment_id\`) REFERENCES \`apartments\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_539cbf8d9c56b56b660efb95f2f\` FOREIGN KEY (\`occupancy_id\`) REFERENCES \`occupancies\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invoices\` ADD CONSTRAINT \`FK_440f531f452dcc4389d201b9d4b\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reminders\` ADD CONSTRAINT \`FK_de7f323194f85398815441bd3a6\` FOREIGN KEY (\`tenant_id\`) REFERENCES \`tenants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reminders\` ADD CONSTRAINT \`FK_abdc6751167a721c09c2830d998\` FOREIGN KEY (\`invoice_id\`) REFERENCES \`invoices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_563a5e248518c623eebd987d43e\` FOREIGN KEY (\`invoice_id\`) REFERENCES \`invoices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TABLE \`query_cache\` (\`id\` int NOT NULL AUTO_INCREMENT, \`identifier\` varchar(255) NULL, \`time\` bigint NOT NULL, \`duration\` int NOT NULL, \`query\` text NOT NULL, \`result\` text NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE \`query_cache\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_563a5e248518c623eebd987d43e\``);
        await queryRunner.query(`ALTER TABLE \`reminders\` DROP FOREIGN KEY \`FK_abdc6751167a721c09c2830d998\``);
        await queryRunner.query(`ALTER TABLE \`reminders\` DROP FOREIGN KEY \`FK_de7f323194f85398815441bd3a6\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_440f531f452dcc4389d201b9d4b\``);
        await queryRunner.query(`ALTER TABLE \`invoices\` DROP FOREIGN KEY \`FK_539cbf8d9c56b56b660efb95f2f\``);
        await queryRunner.query(`ALTER TABLE \`occupancies\` DROP FOREIGN KEY \`FK_e136b5566e6dba72d8f389a68bf\``);
        await queryRunner.query(`ALTER TABLE \`occupancies\` DROP FOREIGN KEY \`FK_c2efa500cba606fc34d8ddaafbe\``);
        await queryRunner.query(`ALTER TABLE \`apartments\` DROP FOREIGN KEY \`FK_55d37c286a265d21050cae70d2a\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_7ae6334059289559722437bcc1c\``);
        await queryRunner.query(`DROP INDEX \`IDX_96dd5920faa78291a24a5df5c5\` ON \`payments\``);
        await queryRunner.query(`DROP INDEX \`IDX_b557b05b082296d4daacaaa5dd\` ON \`payments\``);
        await queryRunner.query(`DROP INDEX \`IDX_66ef2a22355829d25ca16b4d26\` ON \`payments\``);
        await queryRunner.query(`DROP INDEX \`IDX_4781cf05f36ba314cdd314c0c6\` ON \`payments\``);
        await queryRunner.query(`DROP TABLE \`payments\``);
        await queryRunner.query(`DROP INDEX \`IDX_1793350b2155aa2ce6317cf4f7\` ON \`reminders\``);
        await queryRunner.query(`DROP INDEX \`IDX_d61cc4c5af3a45f1b999b5b2c4\` ON \`reminders\``);
        await queryRunner.query(`DROP INDEX \`IDX_e97a544f921f6767cd9f31e767\` ON \`reminders\``);
        await queryRunner.query(`DROP TABLE \`reminders\``);
        await queryRunner.query(`DROP INDEX \`IDX_668775b9dc46cd6402210bd919\` ON \`invoices\``);
        await queryRunner.query(`DROP INDEX \`IDX_c1cc6a2e57fddf1d677f88d7b6\` ON \`invoices\``);
        await queryRunner.query(`DROP INDEX \`IDX_ea4aed7c8a6b574f4d9b79c3bf\` ON \`invoices\``);
        await queryRunner.query(`DROP INDEX \`IDX_c72926e1735b41a93b9c5f57c0\` ON \`invoices\``);
        await queryRunner.query(`DROP INDEX \`IDX_42385e42f092f26bd38df54971\` ON \`invoices\``);
        await queryRunner.query(`DROP TABLE \`invoices\``);
        await queryRunner.query(`DROP INDEX \`IDX_cc30a75ec408eb5b3e40d2ef87\` ON \`tenants\``);
        await queryRunner.query(`DROP INDEX \`IDX_43a378face32c5050980a0f26b\` ON \`tenants\``);
        await queryRunner.query(`DROP INDEX \`IDX_4575399619ef02e945a891594c\` ON \`tenants\``);
        await queryRunner.query(`DROP INDEX \`IDX_a12aa6f8ff1f37c2f46d3c8d2d\` ON \`tenants\``);
        await queryRunner.query(`DROP TABLE \`tenants\``);
        await queryRunner.query(`DROP INDEX \`IDX_32c4561f4cc180f79bc0fdb43f\` ON \`occupancies\``);
        await queryRunner.query(`DROP INDEX \`IDX_4d90e617c11658ff4d517c796c\` ON \`occupancies\``);
        await queryRunner.query(`DROP INDEX \`IDX_cc434c1f52c60c9798f1b78c8a\` ON \`occupancies\``);
        await queryRunner.query(`DROP INDEX \`IDX_ede495d4327cd721ce175a8511\` ON \`occupancies\``);
        await queryRunner.query(`DROP TABLE \`occupancies\``);
        await queryRunner.query(`DROP INDEX \`IDX_febf85cc220bd9dd7944ad9f46\` ON \`apartments\``);
        await queryRunner.query(`DROP INDEX \`IDX_bc79e8864b14bbeec8ea1b3e69\` ON \`apartments\``);
        await queryRunner.query(`DROP INDEX \`IDX_55d37c286a265d21050cae70d2\` ON \`apartments\``);
        await queryRunner.query(`DROP INDEX \`IDX_4c561cc9a0dbc7a155eb67a930\` ON \`apartments\``);
        await queryRunner.query(`DROP TABLE \`apartments\``);
        await queryRunner.query(`DROP INDEX \`IDX_8209df35c059494e5385f81619\` ON \`compounds\``);
        await queryRunner.query(`DROP INDEX \`IDX_3b301e23108ca93e9722cef76f\` ON \`compounds\``);
        await queryRunner.query(`DROP TABLE \`compounds\``);
        await queryRunner.query(`DROP INDEX \`IDX_074675ed1a1d59bfe7bdb9c0a3\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_13af76739939fc5cb3c90ab3e7\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_ace513fa30d485cfd25c11a9e4\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_7ae6334059289559722437bcc1\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_b28b07d25e4324eee577de5496\` ON \`companies\``);
        await queryRunner.query(`DROP TABLE \`companies\``);
    }

}
